<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SaaSBot.Workers-fbf29c94-1f01-4574-83e2-0e2cfeeb870b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaaSBot.Application\SaaSBot.Application.csproj" />
    <ProjectReference Include="..\SaaSBot.Infrastructure\SaaSBot.Infrastructure.csproj" />
    <ProjectReference Include="..\SaaSBot.Agents\SaaSBot.Agents.csproj" />
  </ItemGroup>
</Project>
