<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SaaSBot.Application\SaaSBot.Application.csproj" />
    <ProjectReference Include="..\SaaSBot.Domain\SaaSBot.Domain.csproj" />
    <ProjectReference Include="..\SaaSBot.Infrastructure\SaaSBot.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.44.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
