<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HiveOps.Application\HiveOps.Application.csproj" />
    <ProjectReference Include="..\HiveOps.Domain\HiveOps.Domain.csproj" />
    <ProjectReference Include="..\HiveOps.Infrastructure\HiveOps.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.44.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
